name: Security Scan

on: 
  pull_request: 
    branches: [master]
    types: [opened, synchronize]

jobs: 
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@521761c1a5cf68d919980a2ed84b755182aeabfe # pinned to latest
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'