name: 'PR Validation'
on:
  pull_request_target: 
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pre-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_checks.yml@62909fc10e105bba5cba4ff73b03c020b97789d4 # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'